services:

  # streamlit app
  web: 
    build:
      context: ./app  
    ports:
      - "8501:8501"  
    depends_on:
      - api  
    networks:
      - app-network

  # api
  api:  
    build:
      context: ./api  
    ports:
      - "8000:8000"  
    networks:
      - app-network 

networks:
  app-network:
    # create a bridge network
    driver: bridge
