# version: '3.8'  # Version of the Docker Compose file format

services:
  web:  # Web service for the Streamlit app
    build:
      context: ./app  # Directory where the Dockerfile is located (code/deployment/app)
    ports:
      - "8501:8501"  # Map port 8501 on host to port 8501 on the container
    depends_on:
      - api  # Wait until the API service is up
    networks:
      - app-network  # Define the network for communication with the API service

  api:  # API service (Flask API or other)
    build:
      context: ./api  # Directory where the API's Dockerfile is located (code/deployment/api)
    ports:
      - "5000:5000"  # Map port 5000 on host to port 5000 on the container
    networks:
      - app-network  # Same network for communication

networks:
  app-network:  # Create a custom network for your services
    driver: bridge
