services:
  web: 
    build:
      context: ./app  
    ports:
      - "8501:8501"  
    depends_on:
      - api  
    networks:
      - app-network  

  api:  
    build:
      context: ./api  
    ports:
      - "8000:8000"  
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge
